### ISSUE TITLE
jumper t-20-v2 target shows backpack when it doesn't

### ISSUE THREAD

**Issue by CREASE-gum-EAR** [ExpressLRS/targets#119]
The target below shows backpack as being true but the v2 T-20 does not have a backpack.

"jumper": {
        "name": "Jumper",
        "tx_2400": {
            "t-20-v2": {
                "product_name": "Jumper AION T-20 2.4GHz V2 TX",
                "lua_name": "T-20 2G4 TX",
                "layout_file": "Jumper T-20 2400.json",
                "overlay": {
                    "use_backpack": `true`, (This should be `false`)
                    "misc_fan_en": 33
                },
                "upload_methods": ["uart", "wifi", "etx"],
                "min_version": "3.3.0",
                "platform": "esp32",
                "firmware": "Unified_ESP32_2400_TX",
                "prior_target_name": "Jumper_AION_2400_T-Pro_TX"
            },

**Comment by JyeSmith** [comment]
This piece of hardware was release just before we made a BP mandatory, and put us (and users) in a hard place.

Jumper does offer a plug in BP for the module.  So for now I think it will be better to leave the target as is, instead of disabling the BP and requiring users to change settings in the hardware.html page.

![image](https://github.com/user-attachments/assets/5e0c7898-f559-46c1-b32d-72d2b0e61f96)
